//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_permission()
        {
            this.Client_Quantity = new HashSet<Client_Quantity>();
        }
    
        public int Per_id_C { get; set; }
        public string WH_name { get; set; }
        public int P_code { get; set; }
        public Nullable<System.DateTime> C_per_date { get; set; }
        public Nullable<int> C_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Quantity> Client_Quantity { get; set; }
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
