//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.C_permission = new HashSet<C_permission>();
            this.Client_Quantity = new HashSet<Client_Quantity>();
        }
    
        public int C_id { get; set; }
        public string C_email { get; set; }
        public string C_name { get; set; }
        public Nullable<int> C_fax { get; set; }
        public Nullable<int> C_mob_num { get; set; }
        public Nullable<int> C_tel_num { get; set; }
        public string C_website { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_permission> C_permission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Quantity> Client_Quantity { get; set; }
    }
}
