//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Quantity
    {
        public string WH_Name { get; set; }
        public int P_code { get; set; }
        public Nullable<int> C_id { get; set; }
        public int quantity { get; set; }
        public int Per_id_C { get; set; }
    
        public virtual C_permission C_permission { get; set; }
        public virtual Client Client { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Product Product { get; set; }
    }
}
