//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xCompany
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Linq_ProjectEntities3 : DbContext
    {
        public Linq_ProjectEntities3()
            : base("name=Linq_ProjectEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_permission> C_permission { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Client_Quantity> Client_Quantity { get; set; }
        public virtual DbSet<Prod_Measure> Prod_Measure { get; set; }
        public virtual DbSet<prod_Transfer> prod_Transfer { get; set; }
        public virtual DbSet<prod_WareHouse> prod_WareHouse { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<S_permission> S_permission { get; set; }
        public virtual DbSet<Sup_Quantity> Sup_Quantity { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
    }
}
