//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_Measure
    {
        public string Measure_Unit { get; set; }
        public int P_code { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
