//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class prod_Transfer
    {
        public int transferID { get; set; }
        public string from_wh { get; set; }
        public string to_wh { get; set; }
        public Nullable<int> p_code { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> supplierID { get; set; }
        public Nullable<System.DateTime> transferDate { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
