//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.prod_Transfer = new HashSet<prod_Transfer>();
            this.S_permission = new HashSet<S_permission>();
            this.Sup_Quantity = new HashSet<Sup_Quantity>();
        }
    
        public int S_id { get; set; }
        public string S_email { get; set; }
        public string S_name { get; set; }
        public Nullable<int> S_fax { get; set; }
        public Nullable<int> S_mob_num { get; set; }
        public Nullable<int> S_tel_num { get; set; }
        public string S_website { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prod_Transfer> prod_Transfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_permission> S_permission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sup_Quantity> Sup_Quantity { get; set; }
    }
}
